### ISSUE TITLE
Create reviewers model

### ISSUE THREAD

**Issue by ryan95f** [Ryan95Z/Module-Summary-Change-Management-System#2]
Create a django model 'Reviewers'

**Comment by iwanfrancis** [comment]
I've created the model. At the moment it's pretty much the same as the year tutor, just that the user is associated with a module code instead of a year, but it can be easily expanded when we determine what else needs to be considered. 

The model actually uses a foreign key to associate itself with a module - this is a one to many relationship, which may not be correct. We need to confirm whether module reviewers are restricted to a single module or whether they can review many.

Working on tests at the moment.

**Comment by iwanfrancis** [comment]
So I've changed the model again so that the user is now a one-to-one relation, and modules can be many to many. This means that there can't be multiple reviewer objects for the same person. The list view now shows a comma separated list of modules to reflect this change.

I'm going to mark this as done for now, but I'll just do a few more tests before I start another task.

**Comment by ryan95f** [comment]
Can we close this task for now?
